// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_smarter_RCPPEXPORTS_H_GEN_
#define RCPP_smarter_RCPPEXPORTS_H_GEN_

#include <RcppArmadillo.h>
#include <Rcpp.h>

namespace smarter {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("smarter", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("smarter", "_smarter_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in smarter");
            }
        }
    }

    inline double Rcpp_logSumExp(const arma::vec& log_x) {
        typedef SEXP(*Ptr_Rcpp_logSumExp)(SEXP);
        static Ptr_Rcpp_logSumExp p_Rcpp_logSumExp = NULL;
        if (p_Rcpp_logSumExp == NULL) {
            validateSignature("double(*Rcpp_logSumExp)(const arma::vec&)");
            p_Rcpp_logSumExp = (Ptr_Rcpp_logSumExp)R_GetCCallable("smarter", "_smarter_Rcpp_logSumExp");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_Rcpp_logSumExp(Shield<SEXP>(Rcpp::wrap(log_x)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<double >(rcpp_result_gen);
    }

    inline void Rcpp_round(arma::vec& vv, const arma::uword& digits) {
        typedef SEXP(*Ptr_Rcpp_round)(SEXP,SEXP);
        static Ptr_Rcpp_round p_Rcpp_round = NULL;
        if (p_Rcpp_round == NULL) {
            validateSignature("void(*Rcpp_round)(arma::vec&,const arma::uword&)");
            p_Rcpp_round = (Ptr_Rcpp_round)R_GetCCallable("smarter", "_smarter_Rcpp_round");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_Rcpp_round(Shield<SEXP>(Rcpp::wrap(vv)), Shield<SEXP>(Rcpp::wrap(digits)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
    }

    inline void Rcpp_chk_threads(const arma::uword& NN, const int& ncores = 1) {
        typedef SEXP(*Ptr_Rcpp_chk_threads)(SEXP,SEXP);
        static Ptr_Rcpp_chk_threads p_Rcpp_chk_threads = NULL;
        if (p_Rcpp_chk_threads == NULL) {
            validateSignature("void(*Rcpp_chk_threads)(const arma::uword&,const int&)");
            p_Rcpp_chk_threads = (Ptr_Rcpp_chk_threads)R_GetCCallable("smarter", "_smarter_Rcpp_chk_threads");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_Rcpp_chk_threads(Shield<SEXP>(Rcpp::wrap(NN)), Shield<SEXP>(Rcpp::wrap(ncores)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
    }

}

#endif // RCPP_smarter_RCPPEXPORTS_H_GEN_
