// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_smartr_RCPPEXPORTS_H_GEN_
#define RCPP_smartr_RCPPEXPORTS_H_GEN_

#include <RcppArmadillo.h>
#include <Rcpp.h>

namespace smartr {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("smartr", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("smartr", "_smartr_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in smartr");
            }
        }
    }

    inline double _logSumExp(const arma::vec& log_x) {
        typedef SEXP(*Ptr__logSumExp)(SEXP);
        static Ptr__logSumExp p__logSumExp = NULL;
        if (p__logSumExp == NULL) {
            validateSignature("double(*_logSumExp)(const arma::vec&)");
            p__logSumExp = (Ptr__logSumExp)R_GetCCallable("smartr", "_smartr__logSumExp");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p__logSumExp(Shield<SEXP>(Rcpp::wrap(log_x)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<double >(rcpp_result_gen);
    }

}

#endif // RCPP_smartr_RCPPEXPORTS_H_GEN_
