# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Rcpp_logSumExp <- function(log_x) {
    .Call('_smarter_Rcpp_logSumExp', PACKAGE = 'smarter', log_x)
}

Rcpp_round <- function(vv, digits) {
    invisible(.Call('_smarter_Rcpp_round', PACKAGE = 'smarter', vv, digits))
}

Rcpp_chk_threads <- function(NN, ncores = 1L) {
    invisible(.Call('_smarter_Rcpp_chk_threads', PACKAGE = 'smarter', NN, ncores))
}

