# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Rcpp_logSumExp <- function(log_x) {
    .Call('_smartr_Rcpp_logSumExp', PACKAGE = 'smartr', log_x)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_smartr_RcppExport_registerCCallable', PACKAGE = 'smartr')
})
